### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ksindy** [GeneMANIA/genemania#118]
We have noticed a memory leak with Genemania that forces the need to reboot the app. To test the memory leak we set up a scheduled curl command to hit genemania everyone minute with one human gene symbol from a list of 10k unique symbols. Here is what we found:

0h 1.369gb free
2h 1.273gb free
3h 1.213gb free
20h 0.998gb free

With a total loss of 0.398gb after 20hours. We wanted you to be aware of this in case you were not already. Thanks!

**Comment by maxkfranz** [comment]
The app uses a lot of caching.  It's expected to increase in memory usage over time.  Eventually it should reach a plateau when the caches get maxed out, but that can take some time and it depends on user queries.

**Comment by ksindy** [comment]
ah ok. Thanks for the reply.
