### ISSUE TITLE
Differences in gene name and query term while retrieving genemania network thrrough Cytoscape

### ISSUE THREAD

**Issue by Niveda-S** [GeneMANIA/genemania#129]
I use the cytoscape app to construct a gene network. In some cases, the query term I put in does not exactly match the gene name retrieved by genemania.  It looks like the synonyms are being considered to match gene name to query term. I was wondering on what basis the synonym is being considered. For example in my case, 

```
SUID | annotation name | annotations | log score | name | gene name | query term | node type | score | selected | shared name | Synonym
6557 |   |   | -0.48442 | H__sapiens__5_-702658 | query | DNAJA1 | HSJ2 | 0.616054 | FALSE | H__sapiens__5_-702658 | HSJ2

6567 |   |   | -0.414 | H__sapiens__5_-704214 | query | DNAJB6 | MRJ | 0.660998 | FALSE | H__sapiens__5_-704214 | MRJ
```

Genemania considers HSJ2 and DNAJA1 to be synonyms and MRJ and DNAJB6 to be synonyms and considers that MRJ and HSJ2 interact with one another.

But, Uniprot considers MRJ, HSJ2 and DNAJB6 to be synonyms with Uniprot ID = O75190
I'm not sure how to deal with a situation like this. Because O75190 is my protein of interest, is it valid to show that synonymous genes interact with one another? Or should I discount cases of synonymous gene interactions?

**Comment by gbader** [comment]
Hi - GeneMANIA gets its synonym information from the Ensembl database and Ensembl only lists HSJ2 for DNAJA1.  It is strongly recommended that you should use the official gene symbols or a corresponding unique database identifier (e.g. entrez gene) and never use synonyms in any of your work (even though genemania will try to recognize synonyms).  If the same synonym is used for two different genes in the literature, then you will need to consider that in your interpretation of associated data as there is always the chance for mistakes and there are many examples where such mistakes have been made e.g. https://www.nature.com/articles/nature02141  Problems like this may require you to go back to the original journal articles to verify the exact gene sequences and accession numbers to check for mistakes that unfortunately propagate to many databases.

Best,
Gary

**Comment by Niveda-S** [comment]
Thanks for the response! I would like further clarification on the following:

1) I have a list of protein ids that I would like to use as input for genemania. I have noticed that using protein ids as opposed to the official gene symbols of the proteins gives slightly varied responses. Which method do you suggest I use?

2) Also, in the case I described above:
```
SUID | annotation name | annotations | log score | name | gene name | query term | node type | score | selected | shared name | Synonym
6557 |   |   | -0.48442 | H__sapiens__5_-702658 | query | DNAJA1 | HSJ2 | 0.616054 | FALSE | H__sapiens__5_-702658 | HSJ2
6567 |   |   | -0.414 | H__sapiens__5_-704214 | query | DNAJB6 | MRJ | 0.660998 | FALSE | H__sapiens__5_-704214 | MRJ
```
should I be using the query term or the gene term as the interactor names?

Thanks,
Niveda
