### ISSUE TITLE
Export results - in Genemania results panel menu - exports empty file

### ISSUE THREAD

**Issue by risserlin** [GeneMANIA/genemania#194]
<img width="429" alt="Screen Shot 2022-10-06 at 9 18 18 AM" src="https://user-images.githubusercontent.com/3842763/194323164-17943b85-d6db-462c-9e26-17098bc1969d.png">

Results file that is exported is empty.

No errors consoles coming up.  Also, nothing in the cytoscape framework file.

**Comment by chrtannus** [comment]
I noticed this only happens with the networks from online searches (the search bar in the Network control panel).

**Comment by chrtannus** [comment]
Fixed in version `3.5.3`.
